CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    key_prefix VARCHAR(20) NOT NULL,
    key_hash CHAR(64) NOT NULL,
    scopes TEXT NULL,
    last_used_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_api_keys_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_api_keys_hash UNIQUE (key_hash),
    CONSTRAINT uq_api_keys_user_name UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys (user_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_prefix ON api_keys (key_prefix);
CREATE INDEX IF NOT EXISTS idx_api_keys_expires ON api_keys (expires_at);
CREATE INDEX IF NOT EXISTS idx_api_keys_revoked ON api_keys (revoked_at);

CREATE TABLE IF NOT EXISTS rate_limits (
    bucket_key BYTEA PRIMARY KEY,
    attempts INTEGER NOT NULL DEFAULT 0,
    window_started_at TIMESTAMP NOT NULL,
    last_attempt_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_rate_limits_bucket_key_length CHECK (octet_length(bucket_key) = 32),
    CONSTRAINT chk_rate_limits_attempts_nonnegative CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_rate_limits_last_attempt ON rate_limits (last_attempt_at);
CREATE INDEX IF NOT EXISTS idx_rate_limits_window ON rate_limits (window_started_at);
