CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT NULL,

    value_type VARCHAR(20) NOT NULL DEFAULT 'string',

    description VARCHAR(255) NULL,

    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    is_editable BOOLEAN NOT NULL DEFAULT TRUE,

    updated_by BIGINT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_system_settings_key UNIQUE (setting_key),

    CONSTRAINT fk_system_settings_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT chk_system_settings_type
        CHECK (value_type IN ('string', 'integer', 'boolean', 'json'))
);

CREATE INDEX IF NOT EXISTS idx_system_settings_public ON system_settings (is_public);
CREATE INDEX IF NOT EXISTS idx_system_settings_editable ON system_settings (is_editable);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_system_settings_updated_at'
          AND tgrelid = 'system_settings'::regclass
    ) THEN
        CREATE TRIGGER trg_system_settings_updated_at
        BEFORE UPDATE ON system_settings
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
    END IF;
END;
$$;
